
package autonoma.sanjose.views;

import autonoma.sanjose.models.Hospital;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author herre
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private JButton btnGestionEmpleados;
    private JButton btnGestionPacientes;
    private JButton btnGestionFarmacia;
    private JButton btnReportes;
    private Hospital hospitalmain;
    private Hospital hospital;

    public VentanaPrincipal() {
        setTitle("Hospital San José St. Bonaventure - Ventana Principal");
        setSize(400, 300);
        setLocationRelativeTo(null); // Centra la ventana
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null); // Usar diseño nulo para posicionar los botones manualmente

        // Inicializar los botones
        btnGestionEmpleados = new JButton("Gestión de Empleados");
        btnGestionEmpleados.setBounds(100, 30, 200, 30);
        btnGestionPacientes = new JButton("Gestión de Pacientes");
        btnGestionPacientes.setBounds(100, 70, 200, 30);
        btnGestionFarmacia = new JButton("Gestión de Farmacia");
        btnGestionFarmacia.setBounds(100, 110, 200, 30);
        btnReportes = new JButton("Generar Reportes");
        btnReportes.setBounds(100, 150, 200, 30);

        // Agregar los botones a la ventana
        add(btnGestionEmpleados);
        add(btnGestionPacientes);
        add(btnGestionFarmacia);
        add(btnReportes);

        // Asignar acciones a los botones para abrir las otras ventanas
        btnGestionEmpleados.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GestionEmpleado gestionEmpleados = new GestionEmpleado();
                gestionEmpleados.setVisible(true);
            }
        });

      

        btnGestionFarmacia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                GestionFarmacia gestionFarmacia = new GestionFarmacia();
                gestionFarmacia.setVisible(true);
            }
        });

        
    }
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Hospital hospital) {
        initComponents();
        this.setLocationRelativeTo(null);
        try{
            this.setIconImage(new ImageIcon(getClass().getResource("/autonoma/DemoTienda/images/tienda.png")).getImage());
        }catch(Exception e){
            
        }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lblNombreHospital = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BtnFarmacia = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BtnPacientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnEmpleado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnCitas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        lblNombreHospital.setFont(new java.awt.Font("Serif", 0, 36)); // NOI18N
        lblNombreHospital.setText("Hospital San José St. Bonaventure");

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setText("Vidal Antonio Morales - Angie Herrera Villa ");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hospital.png"))); // NOI18N
        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(lblNombreHospital))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreHospital)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        BtnFarmacia.setBackground(new java.awt.Color(204, 204, 255));
        BtnFarmacia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnFarmaciaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnFarmaciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnFarmaciaMouseExited(evt);
            }
        });

        jLabel4.setText("FARMACIA ");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/medicamento.png"))); // NOI18N

        javax.swing.GroupLayout BtnFarmaciaLayout = new javax.swing.GroupLayout(BtnFarmacia);
        BtnFarmacia.setLayout(BtnFarmaciaLayout);
        BtnFarmaciaLayout.setHorizontalGroup(
            BtnFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnFarmaciaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnFarmaciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BtnFarmaciaLayout.setVerticalGroup(
            BtnFarmaciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnFarmaciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(17, 17, 17))
        );

        BtnPacientes.setBackground(new java.awt.Color(204, 204, 255));
        BtnPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnPacientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnPacientesMouseExited(evt);
            }
        });

        jLabel5.setText("PACIENTES");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paciente.png"))); // NOI18N

        javax.swing.GroupLayout BtnPacientesLayout = new javax.swing.GroupLayout(BtnPacientes);
        BtnPacientes.setLayout(BtnPacientesLayout);
        BtnPacientesLayout.setHorizontalGroup(
            BtnPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnPacientesLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnPacientesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(28, 28, 28))
        );
        BtnPacientesLayout.setVerticalGroup(
            BtnPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnPacientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        BtnEmpleado.setBackground(new java.awt.Color(204, 204, 255));
        BtnEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEmpleadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnEmpleadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnEmpleadoMouseExited(evt);
            }
        });

        jLabel6.setText("EMPLEADO");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleados.png"))); // NOI18N

        javax.swing.GroupLayout BtnEmpleadoLayout = new javax.swing.GroupLayout(BtnEmpleado);
        BtnEmpleado.setLayout(BtnEmpleadoLayout);
        BtnEmpleadoLayout.setHorizontalGroup(
            BtnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnEmpleadoLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(BtnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEmpleadoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        BtnEmpleadoLayout.setVerticalGroup(
            BtnEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnEmpleadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        BtnCitas.setBackground(new java.awt.Color(204, 204, 255));
        BtnCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BtnCitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BtnCitasMouseExited(evt);
            }
        });

        jLabel7.setText("CITAS");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N

        javax.swing.GroupLayout BtnCitasLayout = new javax.swing.GroupLayout(BtnCitas);
        BtnCitas.setLayout(BtnCitasLayout);
        BtnCitasLayout.setHorizontalGroup(
            BtnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnCitasLayout.createSequentialGroup()
                .addGroup(BtnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BtnCitasLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel7))
                    .addGroup(BtnCitasLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        BtnCitasLayout.setVerticalGroup(
            BtnCitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BtnCitasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(BtnFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(BtnCitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnFarmacia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFarmaciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFarmaciaMouseEntered
        this.mouseEntered(BtnFarmacia);
    }//GEN-LAST:event_BtnFarmaciaMouseEntered

    private void BtnFarmaciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFarmaciaMouseExited
         this.mouseExited(BtnFarmacia);
    }//GEN-LAST:event_BtnFarmaciaMouseExited

    private void BtnPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPacientesMouseEntered
         this.mouseEntered(BtnPacientes);
    }//GEN-LAST:event_BtnPacientesMouseEntered

    private void BtnPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPacientesMouseExited
        this.mouseExited(BtnPacientes);
    }//GEN-LAST:event_BtnPacientesMouseExited

    private void BtnEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadoMouseExited
        this.mouseExited(BtnEmpleado);
    }//GEN-LAST:event_BtnEmpleadoMouseExited

    private void BtnEmpleadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadoMouseEntered
        this.mouseEntered(BtnEmpleado);
    }//GEN-LAST:event_BtnEmpleadoMouseEntered

    private void BtnCitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCitasMouseEntered
        this.mouseEntered(BtnCitas);
    }//GEN-LAST:event_BtnCitasMouseEntered

    private void BtnCitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCitasMouseExited
        this.mouseExited(BtnCitas);
    }//GEN-LAST:event_BtnCitasMouseExited

    private void BtnFarmaciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnFarmaciaMouseClicked
        GestionFarmacia ventanaFarmacia = new GestionFarmacia ( this, true ,this.hospital,this);
        ventanaFarmacia.setVisible(true);
    }//GEN-LAST:event_BtnFarmaciaMouseClicked

    private void BtnPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnPacientesMouseClicked
        
        
    }//GEN-LAST:event_BtnPacientesMouseClicked

    private void BtnEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEmpleadoMouseClicked
      GestionEmpleado ventanaEmpleado = new GestionEmpleado (this,true,this.hospital,this);
      ventanaEmpleado.setVisible(true);
    }//GEN-LAST:event_BtnEmpleadoMouseClicked
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnCitas;
    private javax.swing.JPanel BtnEmpleado;
    private javax.swing.JPanel BtnFarmacia;
    private javax.swing.JPanel BtnPacientes;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNombreHospital;
    // End of variables declaration//GEN-END:variables

    private void mouseEntered(JPanel panel) {
       panel.setBackground(new Color(200,255,255));
    }

    private void mouseExited(JPanel panel) {
        panel.setBackground(new Color(255,255,255));
    }

}
